### ISSUE TITLE
Why white space in text field

### ISSUE THREAD

**Issue by 88srzh** [catppuccin/thunderbird#3]
![Screenshot_123](https://user-images.githubusercontent.com/61797666/213425701-88936488-01cc-4ab5-a833-2980595dd33e.jpg)
looks not good :(

**Comment by elkrien** [comment]
It something that is not managed by .xpi (theme file) but needs to be managed by css which isn't a part of this theme.

**Comment by nullishamy** [comment]
Without doing something akin to the "Dark Reader" browser extension, this is not possible. There are other Thunderbird addons that provide a dark mode for the content view.
