### ISSUE TITLE
Theming the "Spaces Toolbar"

### ISSUE THREAD

**Issue by nullishamy** [catppuccin/thunderbird#4]
By default, the themes here do not theme the "Spaces Toolbar" (pictured below, themed manually).

By right clicking => customise, the user can set the relevant colours.
If this cannot be themed by an xpi, this process should probably be documented in the README. Otherwise, it would be good to set it up automatically!

![image](https://user-images.githubusercontent.com/99221043/216128477-206086a2-7275-4ef7-9083-d55473f5df9e.png)

**Comment by khaneliman** [comment]
Looks like several pieces can't be colored from the xpi anymore. I had to resort to using a userChrome.css for some stuff.

**Comment by nullishamy** [comment]
Damn, that sucks. Perhaps a note on that one specifically might be good? Only because it's quite noticeable and not hard to change.
