### ISSUE TITLE
inbox and menu over email not being themed

### ISSUE THREAD

**Issue by BPplays** [catppuccin/thunderbird#6]
the inbox and the menu over emails are not being themed

![tb-out](https://cdn.discordapp.com/attachments/351325708037128202/1158278149767974953/tb-out.png?ex=651baa16&is=651a5896&hm=12bac5df65572d4cdda4167c5739afa0135b75b241880efd0a991162b2da0f78&)

**Comment by nullishamy** [comment]
Can you repost this image? The link is dead.

**Comment by BPplays** [comment]
here is a new image:
![a](https://cdn.discordapp.com/attachments/351325525886763008/1211944553855062016/Screenshot_2024-02-26_214354.png?ex=65f00a52&is=65dd9552&hm=36642240d283121f6fb38fcdf0b347bdc3b82c796f7b1ff00e55094c08da8f09&)

**Comment by nullishamy** [comment]
The panel on the left is fixed in the new version. The email header is still WIP at this stage. See #10 .
